apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ogt4fdaas-go 
  janus-idp.io/tekton: ogt4fdaas-go
  backstage.io/kubernetes-id: ogt4fdaas-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ogt4fdaas-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml