apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ogt4fdaas-go-gitops
  description: This is GitOps manifest for ogt4fdaas-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ogt4fdaas-go
    backstage.io/kubernetes-id: ogt4fdaas-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ogt4fdaas-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ogt4fdaas-go
