apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ogt4fdaas-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:67ea26645642d6d21fef292a0d7647f7fade4a7a@sha256:27439762178de340353aa2b3a55da581f9e45af5ce9bcc1b8d9daa0d3feb4e39
          name: container-image
